### ISSUE TITLE
2nd spawn of a container on a Ph5 RC vm fails

### ISSUE THREAD

**Issue by dcasota** [vmware-samples/photon-os-container-builder#22]
### Describe the bug

2nd spawn of a container on Ph5 RC RT vm fails in the environment described in the reproduction steps.
The screen output logfile (see in reproduction steps) throws out several issues.

1.  command not found `cp: command not found`, `openssl: command not found`
2.  package dependencies
`package cloud-init-23.1.1-2.ph4.noarch requires python3, but none of the providers can be installed`
`package shadow-4.8.1-3.ph4.x86_64 requires cracklib, but none of the providers can be installed`
`package open-vm-tools-12.2.0-1.ph4.x86_64 requires openssl, but none of the providers can be installed`
`package python3-libs-3.10.0-10.ph4.x86_64 requires /usr/bin/python, but none of the providers can be installed`
`package systemd-247.13-2.ph4.x86_64 requires gnutls, but none of the providers can be installed`
`package openssh-8.8p1-5.ph4.x86_64 requires openssl, but none of the providers can be installed`
`package python3-3.10.0-10.ph4.x86_64 requires openssl, but none of the providers can be installed`
`package rpm-4.16.1.3-16.ph4.x86_64 requires openssl >= 1.1.1, but none of the providers can be installed`
`package python3-xml-3.10.0-10.ph4.x86_64 requires python(abi) = 3.10, but none of the providers can be installed`
`package dbus-1.13.18-3.ph4.x86_64 requires systemd, but none of the providers can be installed`
`package curl-8.0.1-1.ph4.x86_64 requires openssl, but none of the providers can be installed`
`package krb5-1.17-9.ph4.x86_64 requires openssl, but none of the providers can be installed`
`package tdnf-3.3.8-2.ph4.x86_64 requires librpmio.so.9()(64bit), but none of the providers can be installed`
3.  Assumption of static ip
`Failed to create unit file for 'photon4': chmod /var/lib/machines/photon4/lib/systemd/network/10-photon4.network: no such file or directory`

The main topic is release-consistency. How is it guaranteed that provisioning (spawn+boot+start) of a container always starts the same bits ?
Is ``cntrctl spawn photon4` equivalent to "spawn latest" ? This is okay, but for testing purposes release-consistency should be the default.

### Reproduction steps

1.  VMware Workstation 17, provisioned vm from `photon-5.0-4d5974638.x86_64.iso` with 2GB RAM + 50GB disk + SATA Controller + USB 3.1
2.  Before Ph5 GA, to update Ph5RC with the latest commits, run :
```
cat <<EOF_REPO > /etc/yum.repos.d/photon-dev.repo
[photon-dev]
name=VMware Photon Linux \$releasever dev (\$basearch)
baseurl=https://packages.vmware.com/photon/dev/latest/photon_dev_\$basearch
pgpkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY-4096
pgpcheck=1
enabled=1
EOF_REPO
tdnf makecache
tdnf update -y
tdnf install -y photon-os-container-builder
```
3.  run `tdnf install systemd-container`
4. run `cntrctl spawn photon5`
5. run `cntrctl boot photon5`, 3x ctrl-]
6. run `cntrctl spawn photon4`
7. see screen output logfile [container spawn](https://github.com/vmware-samples/photon-os-container-builder/files/11242263/ph4.container.spawn.txt)

### Expected behavior

Successfully provision containers.

**Comment by ssahani** [comment]
This more looks like tdnf temp issue.

```
❯ sudo cntrctl start photon51
❯ sudo cntrctl start photon5
❯ machinectl
MACHINE  CLASS     SERVICE        OS     VERSION ADDRESSES
photon5  container systemd-nspawn photon 4.0     -
photon51 container systemd-nspawn photon 4.0     -

2 machines listed.

```

I am able to do

**Comment by dcasota** [comment]
Susant you're right with the temp issue. I couldn't reproduce it today, meanwhile however there were new ph commits e.g. [about `cp` ](https://github.com/vmware/photon/commit/f404f68dd533d23883fedf7f435d35a017cc4855) or [about `cpio`](https://github.com/vmware/photon/commit/1ca6087dfad20ab08d2b3f16fe2704c2bc2d3dd4). It's good if the issue(s) has/have been found! Not 100% reproducible issues are pita.

Photon-os-container-builder's purpose is testing. Therefore first I thought that the cntrctl spawn parameter is a sort of os version and not the container name + hostname. My bad.
Of course, ~container's release-build-entrypoint isn't the main testing purpose.

The following container interactive topics are a little bit confusing:
-  Not an issue, ongoing dev: `machinectl` shows version 4.0, and the boot console output is `Welcome to Photon 4.0 (x86_64) - Kernel 6.1.10-6.ph5-rt (console)`.
-  `tdnf --releasever 5.0 [command]` sometimes shows weired issues e.g. `tdnf --releasever 5.0 install usbutils`, see [container install usbutils - output](https://github.com/vmware-samples/photon-os-container-builder/files/11255574/container.install.usbutils.txt) or `tdnf --releasever 5.0 install open-vm-tools` (warnings `/sbin/ldconfig: /usr/lib/ld-linux-x86-64.so.2 is not a symbolic link`).
-  Avoid additional special characters e.g. `¨`. By typo I was able to start a container `¨ph5`, but when stopping it, it displays `Container ph5 terminated by signal KILL.`

please, close the ticket as you see fit.
